### ISSUE TITLE
在直播间网页全屏模式时，视频下面的礼物栏还是去不掉。

### ISSUE THREAD

**Issue by itheabyss** [festoney8/bilibili-cleaner#101]
不用网页全屏，礼物栏隐藏后没问题，但是选择网页全屏或者全屏时，下面的礼物又出来了。如图：

![screenshot-1720445362222](https://github.com/festoney8/bilibili-cleaner/assets/21150155/c61d2a42-d371-4e36-a975-31ade3075232)

**Comment by festoney8** [comment]
![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/abe6e70c-a7ba-4e0d-9d8a-3a33d7c28395)

**Comment by itheabyss** [comment]
感谢，竟然还有这功能，一直不知道，这个issue提得有点弱了哈
