### ISSUE TITLE
功能请求：能否只保留搜索框，其他板块如首页全部去掉

### ISSUE THREAD

**Issue by whitewatercn** [festoney8/bilibili-cleaner#102]
这样就变成一个纯粹的资料搜索网站了，现在每次去首页还是经常被推荐内容吸引
感谢大佬

**Comment by festoney8** [comment]
直接把纯净搜索页 https://search.bilibili.com/all 当成 B 站主页存进浏览器就行

**Comment by whitewatercn** [comment]
> 直接把纯净搜索页 https://search.bilibili.com/all 当成 B 站主页存进浏览器就行

我去大佬回复好快，

我弄了个[浏览器插件redirector](https://microsoftedge.microsoft.com/addons/detail/redirector/jdhdjbcalnfbmfdpfggcogaegfcjdcfp)也实现这个需求了，谢谢大佬！
