### ISSUE TITLE
评论的图片比例变形了

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#105]
B站给评论里的图片同时设置宽度和高度，扭曲了图片比例。

扭曲比例
![image](https://github.com/user-attachments/assets/9a32581f-d792-4b25-a693-3025c2d6e8de)

正确比例
![image](https://github.com/user-attachments/assets/e7b39213-6999-4d96-9a2a-d08e0c029dd8)

**Comment by festoney8** [comment]
没能复现，能否给一个视频链接

想不出我的脚本里有哪个功能会影响笔记中的图片长宽

**Comment by festoney8** [comment]
> 不好意思没说清楚。这个是B站本身的问题——评论里的单张竖条图片不管什么比例，都被设置成同一个尺寸，导致比例变形。
> 
> [这个视频](https://www.bilibili.com/video/BV1Ji421h74e)有不少带图评论，可以看到变形的竖条图
> 
> 在devtool样式里直接给元素加一个 `width: unset;` 可以解决，但我尝试在stylus加样式时却好像选不中那些img元素。
> 
> 想问下脚本能不能给它优化一下？

最近先暂时忽略一下评论区的各种故障吧，B 站正在测试它的新版评论区，把各种评论区相关插件全干崩了，有 bug 等官方自己挨个修（比如图片问题，头像忽大忽小之类的）

如果你 devtools 里看见评论区的元素有很多层 `#shadow-root (open)` 说明已经是新版评论区，stylus 不会再生效的，具体可以了解一下 [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM)
