### ISSUE TITLE
作者可以增加一个屏蔽5级以下用户的功能吗  这样做可以屏蔽非常多的色情引流信息 或者完全的未成年。

### ISSUE THREAD

**Issue by wmtxdy** [festoney8/bilibili-cleaner#108]

**Comment by festoney8** [comment]
请问是屏蔽首页视频还是评论区屏蔽

**Comment by wmtxdy** [comment]
从b站的首页推荐视频机制来说 3级以下可以过滤非常多的低质视频
评论区和弹幕来说 5级以下可以过滤
希望您可以看下实现哪个难度比较容易。

**Comment by wmtxdy** [comment]
我看了其他的插件  似乎也没有直播间强制最大画质的选项

**Comment by festoney8** [comment]
> 从b站的首页推荐视频机制来说 3级以下可以过滤非常多的低质视频 评论区和弹幕来说 5级以下可以过滤 希望您可以看下实现哪个难度比较容易。

B 站首页推荐视频接口不提供 UP 主的等级，所以首页按等级过滤无法实现

评论区按等级过滤可以做到

> 我看了其他的插件 似乎也没有直播间强制最大画质的选项

这个我试一下可行性，或许可以做

**Comment by wmtxdy** [comment]
好的 谢谢您  按视频发布时间屏蔽过时的视频推荐 和 重复屏蔽来自某一up视频则自动将up加入黑名单 就更好了。 
(●♡ᴗ♡●)

**Comment by festoney8** [comment]
v3.9.2 新增了直播画质自动调最高，评论区按等级过滤，可以测试一下是否生效

**Comment by wmtxdy** [comment]
评论区按等级过滤  没有生效。

**Comment by festoney8** [comment]
> 评论区按等级过滤 没有生效。

试一下 [v3.10.0](https://github.com/festoney8/bilibili-cleaner/releases/tag/v3.10.0) 的评论区按等级过滤会生效吗？注意一下有没有白名单影响。这一版本给首页增加了发布日期过滤，可以试试看

**Comment by wmtxdy** [comment]
好的 现在就试试
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 中午1:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] 作者可以增加一个屏蔽5级以下用户的功能吗  这样做可以屏蔽非常多的色情引流信息 或者完全的未成年。 (Issue #108)














  
评论区按等级过滤 没有生效。
  
试一下预发布版本 v3.10.0 的评论区按等级过滤会生效吗？注意一下有没有白名单影响。这一版本给首页增加了发布日期过滤，可以试试看
