### ISSUE TITLE
播放器相关功能失效 问题反馈

### ISSUE THREAD

**Issue by festoney8** [festoney8/bilibili-cleaner#110]
### **请提供下列信息：**

- 无法生效的功能类型：弹窗相关、控制按钮相关、弹幕相关等
- 浏览器：名称、版本
- 插件管理器：名称、版本
- 播放器 HTML 源码（文件形式），按下方步骤操作

### **如何获取播放器 HTML 源码：**

1. 如果是净化功能失效，在出现无法屏蔽的元素时暂停视频

2. 打开浏览器调试工具 Console 页面，操作方法可参考 [文章](https://balsamiq.com/support/faqs/browserconsole/)

3. 在 Console 中输入下方代码，按回车
```JavaScript
document.querySelector('#playerWrap, .player-wrap').innerHTML
```

4. 将 Console 中打印的大量文本内容**全部复制**，新建一个空白记事本文件，粘贴进去并保存

5. 将该文件以附件形式上传到 Github issue 回复内

![image](https://github.com/user-attachments/assets/5b74b5a7-31b7-40c3-88c0-f8adfdaa3cf0)

**Comment by qilinXBB** [comment]
无法屏蔽的弹窗类型：三连、投票、评分、视频预告、视频链接（其余暂未遇到）
浏览器：Safari 17.5
插件管理器：Tampermonkey v5.2.6199
[播放器 HTML 源码.txt](https://github.com/user-attachments/files/16325330/HTML.txt)

**Comment by festoney8** [comment]
> 无法屏蔽的弹窗类型：三连、投票、评分、视频预告、视频链接（其余暂未遇到） 浏览器：Safari 17.5 插件管理器：Tampermonkey v5.2.6199

感谢反馈，已明确原因。这个 HTML 源码和我这里的结构不同，各种弹窗名都不一样，B 站又在测试播放器里的新东西了

**Comment by festoney8** [comment]
已发布 v3.9.3 尝试适配新弹窗

**Comment by qilinXBB** [comment]
> 已发布 v3.9.3 尝试适配新弹窗

感谢！可以正常过滤了。辛苦了
