### ISSUE TITLE
想问一下怎么进入频道页？

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#116]
> 3.10.0
新增：首页、频道页视频过滤支持发布日期过滤

看到给频道页新增了功能。这个频道页还在吗，怎么进入呀？

之前B站刚移除首页的频道入口时，还能通过bilibili.com/v/channel直接打开频道页，后来再打开就变成一个搜索页了。搜索到bilibili evolved有给顶栏添加频道的插件，试了一下，结果跟打开bilibili.com/v/channel一样，现在只有一个搜索页。看到这个脚本更新日志还给频道页加了功能，所以想问问怎么进入频道页

**Comment by festoney8** [comment]
啊是这样，我的命名有些歧义，以前的按话题分类的"真频道"已经被官方砍掉，B 站现在把分区页叫 channel 我就跟着它的命名走了
![image](https://github.com/user-attachments/assets/4ceb1486-dbcc-4bc1-a730-10298a5f5ede)
