### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Frisy-x** [festoney8/bilibili-cleaner#121]
![image](https://github.com/user-attachments/assets/ad47c272-64d7-44ce-905e-e662ec249b00)
希望能完全隐藏右侧所有信息，然后视频居中放大。谢谢！

**Comment by Frisy-x** [comment]
如果可以的话，想请您喝一杯咖啡！

**Comment by festoney8** [comment]
完全隐藏右侧很简单，但会产生一个难以修复的宽屏模式 bug，找到解决方法之前暂不纳入插件功能

**以下是屏蔽右栏方法：**
1. 安装浏览器插件 (Stylus)[https://chromewebstore.google.com/detail/clngdbkpkpeebahjckkjfobafhncgmne]
2. 给 B 站播放页新增下方样式，如图
```css
.right-container {
    display: none;
}
```

![image](https://github.com/user-attachments/assets/7326641d-e76b-408c-a7da-ce43c82755a8)

**Comment by festoney8** [comment]
已在 [v3.10.4](https://github.com/festoney8/bilibili-cleaner/releases/tag/v3.10.4) 新增隐藏右栏功能，只对普通播放生效（普通播放隐藏右栏后与宽屏模式相似）

修改播放器宽度可用播放设定中的 "视频宽度调节"

![image](https://github.com/user-attachments/assets/a9802a7f-1c4f-459c-8f3a-6b07b39cb8be)
