### ISSUE TITLE
扩增中栏宽度的功能建议

### ISSUE THREAD

**Issue by archerzhoujj** [festoney8/bilibili-cleaner#122]
能不能减小扩增宽度，并把左侧的直播和右侧的话题向两侧移动，把动态页面铺满整个屏幕？不需要左右两侧的空白。

**Comment by festoney8** [comment]
没太明白向两侧移动是什么意思，目前的扩增中栏宽度就是铺满整个屏幕呀

![image](https://github.com/user-attachments/assets/0b4eb3e5-b5c6-473c-a65a-f1617a97ab4f)

**Comment by archerzhoujj** [comment]
不好意思，原来是其他脚本造成的问题，已解决，谢谢你。
