### ISSUE TITLE
关于视频过滤功能一些想法

### ISSUE THREAD

**Issue by LitVeer** [festoney8/bilibili-cleaner#123]
尝试了关键字与时长过滤，但过滤效果并不那么好

相较于关键字这种精准过滤，能否增加一个分区过滤功能，这样能大范围减少某一类型视频（比如生活区）

技术层面上，我留意到视频分区id是可获取的
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/video/video_zone.md
但大量视频的刷新，可能会造成ip、账号封禁

想请教一下各位和作者的看法

**Comment by festoney8** [comment]
就是因为并发量太大，加上本插件的使用人数较多，瞬时并发和每天给 B 站带来的 API 请求增量都不少，所以不考虑做这一功能。
另一个原因是获取 API 的耗时会让视频消失变慢，检测时间从几毫秒变成几百毫秒

关于你的需求，我推荐用 https://greasyfork.org/zh-CN/scripts/481629 这一脚本，它做了通过 API 获取数据的更多屏蔽规则，按 Tag 屏蔽和竖屏屏蔽都是好功能

![image](https://github.com/user-attachments/assets/d73a50ae-312e-494c-9e50-d51cb7b20223)

**Comment by LitVeer** [comment]
感谢分享

**Comment by nomoremore** [comment]
> 就是因为并发量太大，加上本插件的使用人数较多，瞬时并发和每天给 B 站带来的 API 请求增量都不少，所以不考虑做这一功能。 另一个原因是获取 API 的耗时会让视频消失变慢，检测时间从几毫秒变成几百毫秒
> 
> 关于你的需求，我推荐用 https://greasyfork.org/zh-CN/scripts/481629 这一脚本，它做了通过 API 获取数据的更多屏蔽规则，按 Tag 屏蔽和竖屏屏蔽都是好功能

你好我想问下 ，用这个脚本的人多了是不是也会有上述的问题？我感觉这个脚本刷新视频时的性能一般

**Comment by festoney8** [comment]
> 你好我想问下 ，用这个脚本的人多了是不是也会有上述的问题？我感觉这个脚本刷新视频时的性能一般

会有，那个脚本会并发数十个请求逐一获取视频数据，得到了数据才能执行过滤
