### ISSUE TITLE
直播卡片无法被过滤

### ISSUE THREAD

**Issue by tckntckn** [festoney8/bilibili-cleaner#127]
隐藏直播间推荐功能无效

**Comment by festoney8** [comment]
请提供浏览器版本和插件版本

我这里测试还是生效的，开启后图中这两个直播间直接消失

![](https://github.com/user-attachments/assets/c2ff6c19-6cac-45f8-bd3a-0e61e0f970e2)

**Comment by tckntckn** [comment]
Chrome 版本 128.0.6613.85（正式版本） （64 位）
bilibili 页面净化大师3.10.4

**Comment by tckntckn** [comment]
edge 128.0.2739.42 (正式版本) (64 位) 也复现
![877bfb24939e94e7ded7c7e5892d93b](https://github.com/user-attachments/assets/a9c5268f-9403-4ae6-8cae-9bbe10b57164)
![662ec61044cbc057c129a9cd917b050](https://github.com/user-attachments/assets/7bd9c982-c7ab-49f4-9b3b-47677ea32f28)

**Comment by festoney8** [comment]
试一下开启 "隐藏 分区视频推荐" 后这一直播间是否消失？

**Comment by tckntckn** [comment]
开启 "隐藏 分区视频推荐" 后直播间没了，谢谢。  推荐矩阵上似乎有两种直播间卡片

**Comment by festoney8** [comment]
接下来的版本我增强一下隐藏直播间，把两种卡片都干掉
