### ISSUE TITLE
主页过滤视觉和性能问题

### ISSUE THREAD

**Issue by SoulGI** [festoney8/bilibili-cleaner#131]
首页使用视频过滤，有时页面最后一行倒数几个视频的位置，甚至是整行位置的瀑布流加载动画一直出现，视觉效果不佳（持续白屏）且提高了浏览器占用（没动画时CPU 2% 显示动画40%+）
而且有时需要拉到页面最底部或者滚轮上下滚动数次才会继续加载新视频（不是网络导致加载慢，是只显示动画但不加载）
不知道这个问题能不能在油猴脚本上解决
![image](https://github.com/user-attachments/assets/27a5c35a-38db-4c6f-9cef-913706ec93bf)

**Comment by festoney8** [comment]
按图中开启一下这几项，预加载先不要开启，我怀疑有bug会导致加载出现问题

![image](https://github.com/user-attachments/assets/6aa8c303-43d1-44ee-9d13-3629066c0b1a)

**Comment by SoulGI** [comment]
刚试了一下 只开图里这两个第一个问题解决了 但是第二个问题在打开标题关键词之后就不行了
后面又试了下再打开预加载 占用有点高也有点慢 不过这下就比较接近之前没有用插件前的体验了
应该是关键词太普通 命中的视频太多了 所以白的也多

**Comment by festoney8** [comment]
在 v3.11.2 尝试修了一下预加载，会减少一些页面底部的空白骨架

可能不太稳定（预加载功能很难做）如果加载卡顿，还是不要开启这项功能
