### ISSUE TITLE
[FR] 屏蔽UP主带货评论

### ISSUE THREAD

**Issue by zjns** [festoney8/bilibili-cleaner#133]
带货评论一般接口数据都有特定标识，不知道css样式有没有什么区别，我是通过hook window.fetch对象实现的。
示例视频：https://www.bilibili.com/video/BV1Nm4JeoEwS
贴个我的简易实现仅供参考：
![QQ_1726204832860](https://github.com/user-attachments/assets/f8ff5be3-ba5c-48a1-b880-314ce0fe1ea8)

**Comment by festoney8** [comment]
旧版评论区电商带货可以用 CSS 匹配链接网址隐藏掉，但只对部分网址有效，就没有加这个功能

目前 B 站推广新版评论区，CSS 彻底无法屏蔽这种评论，看起来只能在 hook fetch 里筛掉了

我会在后续版本尝试加这一功能

**Comment by festoney8** [comment]
v3.11.3 的评论过滤器新增了带货评论过滤，还需要测试一段时间

PS. 好像 B 站把电商 URL 统一到了 `b23.tv/mall-` 这一网址下
