### ISSUE TITLE
【BUG】评论区的正则过滤，无法使用【捕获和引用】

### ISSUE THREAD

**Issue by lo52570** [festoney8/bilibili-cleaner#134]
问题：评论区的正则过滤，无法正确使用【捕获和引用】
尝试使用了各种写法来引用，无法生效，如`(内容)`+`\1`或`(?<name>内容)`+`\name`
BUG表现为： 当使用以下规则`(.{1,})(\1){3}`时候， 会把所有评论（不含图片）都屏蔽掉

> 上面的过滤规则：`(.{1,})(\1){3}` ，此规则含义为：同样的字符或字符串连续出现3次以上时候，命中，因此过滤。
在其他测试工具、哔哩弹幕过滤中测试可通过
> `(.{1,})`表示捕获1个字符或者多个字符到`默认组`里
> `(\1){3}`表示引用前面的`默认组`3次
> 示例:
> 例1：`哈哈哈`，命中
> 例2：`我是好人我是好人我是好人我是好人`, 命中
> 例3：`哈不哈哈`，不命中
> 例4：`我是好人我是好人`,不命中

此规则在面对一些大量复制的（找存在感）的评论或弹幕来说, 很好用

测试视频的评论区：https://www.bilibili.com/video/BV1X3WpeTEec/
您可通过上面这个视频的评论区来测试
比如当我想用该规则来屏蔽`加油加油加油加油`时,会错误的把所有评论都过滤掉

**Comment by festoney8** [comment]
感谢反馈，已复现

---

是个很奇特的bug，插件为了给关键词筛选提速，会将所有正则和关键词合并成一句长正则

此时如果包含反向引用的正则前面有其他捕获组，会出现错误捕获的情况，比如 `(abc)|(.+)(\1){3}`，当第一个捕获组未命中时，反向引用了空串导致正则把内容全杀了

临时解决办法，把这句正则写在过滤规则第一行（同时后续正则不再出现反向引用）

后续版本会修复这一问题
