### ISSUE TITLE
[BUG] “全屏或网页全屏 页面可滚动” 开启后视频位置不居中

### ISSUE THREAD

**Issue by zjns** [festoney8/bilibili-cleaner#136]
“全屏或网页全屏 页面可滚动” 开启后视频位置不居中，直接置顶了，视频内容下方区域一片灰，番剧和电影播放都有这个问题，投稿视频没这问题，如下图所示：
<div align="center">
<div>
<img src="https://github.com/user-attachments/assets/25f35847-fa42-493a-aae6-98acde4d21de" width="45%" />
<img src="https://github.com/user-attachments/assets/0fc0921f-f707-4905-9ef0-3d01ff5586db" width="45%" />
</div>
</div>

**Comment by festoney8** [comment]
已复现，下一版本修复

**Comment by zjns** [comment]
@festoney8 又发现了个问题：番剧或电影全屏可滚动后向下滑到视频消失时会自动退出全屏模式，投稿视频不会

**Comment by festoney8** [comment]
> @festoney8 又发现了个问题：番剧或电影全屏可滚动后向下滑到视频消失时会自动退出全屏模式显示小窗，投稿视频不会

的确有这个现象，可惜插件没法解决这个问题

实际上调用 mini 模式的 Player API 时，必定会掉出全屏（可以在 Console 中使用下方语句唤起 mini 模式测试）
```js
window.player.requestStatue(nano.ScreenKind.Mini)
```

不过普通播放页在监听页面滚动时多了一层判断，这里 `isFullPremierePlayer` 疑似是网页全屏或全屏状态的标记

番剧页没有这些，直接强行修改播放器模式了，所以网页全屏滚动会出现 mini 播放器，全屏滚动时直接掉出全屏模式，基本没辙

```js
window.addEventListener("scroll", (function() {
    if (!e.isFullPremierePlayer) {
        var t = document.getElementById("arc_toolbar_report").getBoundingClientRect().top
          , n = e.miniShow;
        e.miniShow = t <= 0,
        // requestMini 会调用 player.requestStatue
        e.isBiliPlayer && e.miniShow !== n && (e.miniShow && e.miniLocal ? e.requestMini() : e.exitMini())
    }
}
```

**Comment by festoney8** [comment]
捞一下旧 issue，新发布的 v4.4.2 已支持网页全屏滚动时显示小窗
