### ISSUE TITLE
数据同步可以用 webdav，或者可以导出

### ISSUE THREAD

**Issue by huanfe1** [festoney8/bilibili-cleaner#137]
插件配置项太多，但现在的同步方法感觉有点笨

不知道这里面是否为全部的配置选项

![image](https://github.com/user-attachments/assets/e0f2d7e6-dd1c-4122-b008-14bfd8dffe13)

如果是，可以加一个 webdav 同步的选项，或者是导出导入 Json 文件的选项

**Comment by huanfe1** [comment]
GM_setValue 存储的数据好像都不会同步

**Comment by festoney8** [comment]
> GM_setValue 存储的数据好像都不会同步

目前**同步脚本**不含 GM_setValue 存储的数据，但**导出到云**是包含这些数据的（但它要手动点击导出和导入，无法定时运行）

这个情况困扰用户至少 8 年了，参考 https://github.com/violentmonkey/violentmonkey/issues/48

在脚本内做云端同步开发难度大且不安全，除了接口对接，还会涉及重要信息存储（比如 webdav 鉴权，drive 的 token），故没有这方面的打算

**Comment by huanfe1** [comment]
json 文件的导入导出呢，感觉这样应该比原来的油猴导出的数据文件小

或者说在 Readme 文件夹里加入直接保存数据的教程，感觉文本应该比 zip 文件好保存

![image](https://github.com/user-attachments/assets/9c5ae69b-e21e-476c-b657-e3aedae29a9a)

**Comment by festoney8** [comment]
> json 文件的导入导出呢，感觉这样应该比原来的油猴导出的数据文件小
> 
> 或者说在 Readme 文件夹里加入直接保存存储数据的教程，感觉文本应该比 zip 文件好保存

好的我在 Readme 新增查看 json 存储数据的教程，好像要开启高级模式才能看见这一入口

油猴插件的导出是考虑了稳定性的操作，代码+数据打包，在导入时覆盖本地代码，目的是避免出现代码和数据版本不一致的不可预测错误，所以打包成了 zip

**Comment by huanfe1** [comment]
好的，辛苦了
