### ISSUE TITLE
“过滤@其他用户的评论”可以限制为过滤只包含@其他用户的评论吗？

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#139]
现在只能把带@的全部过滤，会误杀

**Comment by festoney8** [comment]
![image](https://github.com/user-attachments/assets/382a8c78-b0c1-4d36-8e79-6842a28a0d16)

图中这两种评论，现在都会屏蔽掉，是需要只屏蔽第二个的功能吗？
