### ISSUE TITLE
直播间自己发的弹幕不显示在右侧弹幕列表和滚动弹幕里，但是能够正常发送出去

### ISSUE THREAD

**Issue by Garyllis** [festoney8/bilibili-cleaner#142]
不清楚是哪里出的问题，给直播间相关的选项都关掉了也没解决

**Comment by festoney8** [comment]
没能复现，我这里直播间所有功能全开，自己的弹幕还是可见的

试一下在油猴禁用本脚本，刷新页面后发弹幕是否恢复，再开启本脚本，是否再次出问题？

**Comment by Garyllis** [comment]
就是这样找出来的，给每个脚本都单独关了发弹幕最后试出来是这个脚本的问题，没复现可能是我这里跟其他脚本冲突了？

> 
> 试一下在油猴禁用本脚本，刷新页面后发弹幕是否恢复，再开启本脚本，是否再次出问题？

**Comment by Garyllis** [comment]
确实是跟其他脚本冲突了，关掉另一个也解决了

**Comment by Garyllis** [comment]
https://greasyfork.org/zh-CN/scripts/453468-bilibili-live-banned-danmaku-marker
这个
