### ISSUE TITLE
[Other] 视频负反馈 恢复标题宽度 拆分

### ISSUE THREAD

**Issue by PolarLinda6** [festoney8/bilibili-cleaner#153]
是否可以将隐藏视频负反馈 恢复标题宽度 按钮拆分?

希望在单独启用恢复标题宽度的情况下，将负反馈按钮放置于作者日期那一行

![IMG_20241009_221626.png](https://github.com/user-attachments/assets/4fadd85a-5f83-48e1-836d-2963e7feed88)

**Comment by festoney8** [comment]
可以做到，无需拆分功能，下一版直接新增 "移动位置+恢复标题宽度" 这个开关

![image](https://github.com/user-attachments/assets/263800d4-eaa7-4403-9268-00c93415ff54)
