### ISSUE TITLE
[BUG] Firefox隐藏全部相关视频失效

### ISSUE THREAD

**Issue by ChthollyAoi** [festoney8/bilibili-cleaner#156]
### 问题描述

- **出问题的页面**：（首页 / 播放 / 番剧播放 / 搜索 / 动态 / 分区 / 直播 / 热门 / 空间 / 全部页面，**特殊情况请提供网址**）

- **问题功能名**：

- **问题描述**：

- **截图（可选）**：
![Snipaste_2024-10-10_18-42-17](https://github.com/user-attachments/assets/81643960-9457-4e47-8d8b-aefb7ee10ef3)

### 环境

- **本插件版本**：

- **操作系统**：

- **浏览器及版本**：Firefox 131.0.2

- **脚本管理器及版本（可选）**：暴力猴 2.26.0

### 初步检查（可选）

- 可稳定复现问题：是

- 在脚本管理器内，只启用本脚本时，仍出现问题：未知

- 禁用掉在 B 站页面生效的浏览器插件后，仍出现问题：是

**Comment by festoney8** [comment]
已复现，下一版本修复
