### ISSUE TITLE
[FR] 对隐藏内容，禁止资源的加载

### ISSUE THREAD

**Issue by malagebidi** [festoney8/bilibili-cleaner#157]
（在此描述需要的功能~ 提醒一下，本插件专注于页面净化和优化，新功能以让页面更精简、更好用为主，不考虑给 B 站增加页面组件等工具类功能需求）
例：
隐藏横幅banner后，禁止banner图片的加载
隐藏轮播图后，禁止轮播图片的加载

**Comment by festoney8** [comment]
隐藏横幅 banner 以后图片不会加载（因为是动态载入），隐藏轮播图等其他功能难以做到禁止图片加载，难度高并且负面作用很大不值得做
