### ISSUE TITLE
[BUG] 使用脚本后仍然有赛事相关的推荐

### ISSUE THREAD

**Issue by 971230** [festoney8/bilibili-cleaner#159]
### 问题描述

- **出问题的页面**：首页

- **问题功能名**：无法过滤[赛事]推荐

- **问题描述**：使用脚本后，首页仍然有赛事相关的推荐，并且点击换一换按钮后，排在它前面的视频推荐和它本身有概率不会变化。

- **截图（可选）**：
情况一：
![PixPin_2024-10-13_17-19-32](https://github.com/user-attachments/assets/9977fd81-36c0-462a-8305-c88fbe81138e)

情况二(少见):
![PixPin_2024-10-13_17-13-35](https://github.com/user-attachments/assets/40c8f20d-9a05-43f0-856e-06ff95d2b294)

### 环境

- **本插件版本**：4.0.2

- **浏览器及版本**：chrome 129.0.6668.101

- **脚本管理器及版本（可选）**：Tampermonkey 5.1.1

### 初步检查

- 可稳定复现问题：是

- 在脚本管理器内，只启用本脚本时，仍出现问题：是

- 禁用掉对 B 站生效的浏览器插件后，仍出现问题：是

**Comment by festoney8** [comment]
首页左上角有白色分区标记的不是普通视频，不会进入视频过滤，开启页面净化里的隐藏分区视频，可以把这些全隐藏掉

![image](https://github.com/user-attachments/assets/170d8a28-29a6-4846-a1ca-601441988759)

**Comment by festoney8** [comment]
首页视频有两部分，前 10 个是 feed 视频，后面的全是推荐视频

"换一换" 按钮会刷新前 10 个 feed 视频，如果启用了视频过滤，就会剩下不到 10 个，图中的赛事是推荐位，由于每次换一换前 10 个视频被过滤后的数量变动，所以赛事会在不同的地方出现

**Comment by 971230** [comment]
可以成功隐藏掉分区视频的推荐，但是还是有这个bug，见下图：
![PixPin_2024-10-13_17-45-39](https://github.com/user-attachments/assets/17cec532-2355-4ff9-a038-cfda8d1d002e)

**Comment by festoney8** [comment]
我这里没能复现，目前插件内影响换一换操作的功能很少，感觉可能是其他原因

按 F12 看一下 Console 栏，在点击换一换出问题时，有没有报错？

**Comment by 971230** [comment]
哈哈，有的，不知道是不是咱的脚本日志？
![PixPin_2024-10-13_17-58-28](https://github.com/user-attachments/assets/0d363b3a-aef9-42a9-ac90-6c142a584f4d)

Tampermonkey 里禁用本脚本，刷新，换一换按钮会在刷几次后失效，次数随机。可能不是咱这儿脚本导致的😂，原生就有，我换个浏览器再试试看。

**Comment by 971230** [comment]
试过了，是【Ghostery 跟踪器和广告拦截器】插件的问题，抱歉浪费您的时间了，可以关闭该issue了。感谢作者的耐心解答和开源贡献，比心🫰
