### ISSUE TITLE
[BUG] 启用教本看不到弹幕列表？？？？？

### ISSUE THREAD

**Issue by jcoble173** [festoney8/bilibili-cleaner#160]
[BUG] 启用教本看不到弹幕列表？？？？？
![捕获4](https://github.com/user-attachments/assets/e60def84-920d-4602-bba7-b54eb668a456)
![捕获5](https://github.com/user-attachments/assets/b11bcd36-66af-4e35-9b6f-fdfb5be61760)
![捕获3](https://github.com/user-attachments/assets/26831888-5843-43a7-a59a-f71e6a747980)
教本有问题！！！！！！

![捕获](https://github.com/user-attachments/assets/95b2303c-aa35-4870-a9f5-eeb70220feb8)

![捕获2](https://github.com/user-attachments/assets/505e083d-b512-4113-8123-753f950814af)

**Comment by festoney8** [comment]
点开"页面净化优化"菜单，把这项关掉就行

![image](https://github.com/user-attachments/assets/08adb3c3-3e31-48f4-9fc5-4d08b14c3734)
