### ISSUE TITLE
[Other]页面抖动

### ISSUE THREAD

**Issue by Kodakolor** [festoney8/bilibili-cleaner#165]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/3a33923e-f65e-4289-99e9-8a8c95e2cdc4">

在小窗播放开启的情况下，设置了图中这个选项，会出现页面抖动的情况。往下拉到评论区，评论区的宽度会跳到默认值。
关掉小窗播放，就不会有这个问题。

**Comment by festoney8** [comment]
我这里 Chrome130 和 Firefox131 都没能复现，请提供一下你使用的浏览器版本和脚本管理器版本

**Comment by Kodakolor** [comment]
浏览器版本： Chrome 130
脚本管理器版本：bilibili-cleaner 4.0.2 (Tampermonkey 5.3.1)
小窗播放出现前：
<img width="1822" alt="image" src="https://github.com/user-attachments/assets/52bb7d6b-8a9b-473e-8e49-d74157626a2f">
小窗播放出现后：
<img width="1822" alt="image" src="https://github.com/user-attachments/assets/f4b446be-3b95-4d07-97e8-afb210da9253">

**Comment by festoney8** [comment]
我这里无法复现，请问这一现象是近期出现的还是一直就有?

考虑几个可能，一是插件冲突，试一下只启用本插件时是否有这一情况，二是 B 站在灰度测试播放页改动，影响了插件

**Comment by Kodakolor** [comment]
我一开始用这个脚本的时候就关闭了小窗播放的功能，并且隐藏了小窗播放的按钮，之前使用的时候一直没有出现过这个问题。
只启用本插件也会有这个问题。
重装了Chrome之后重新安装脚本才出现的这个问题，可能是你说的后者的原因。
我这边的复现步骤是：
1. 设定视频宽度调节（比默认的小）
2. 开启小窗播放功能
3. 页面往下拉，小窗出现前，评论区的宽度按设定的出现；小窗出现后，评论区宽度会恢复默认值。
4. 在写本条comment时，新发现：非宽屏模式下的播放器会出现这个问题；宽屏模式以及网页全屏都不会出现这个问题。

**Comment by festoney8** [comment]
把这个功能的代码翻新了一下，试试 [这个build](https://github.com/festoney8/bilibili-cleaner/actions/runs/11647380484)，还有没有这一现象

下载产物并解压，手动复制 bilibili-cleaner.user.js 文件的代码到 Tampermonkey 里更新脚本即可

**Comment by Kodakolor** [comment]
好了！
