### ISSUE TITLE
[FR] 根据动态内容关键词屏蔽动态

### ISSUE THREAD

**Issue by Mlk1225** [festoney8/bilibili-cleaner#166]
- 现状：发现在动态屏蔽设置里面虽然有【屏蔽广告动态】【屏蔽抽奖动态】等设置，关键词屏蔽只支持【屏蔽动态发布者】【屏蔽动态内视频标题】，但还是有部分广告动态没有屏蔽（如下图所示），因此想请求能【根据动态内容中的关键词屏蔽某些动态】，
    - ![image](https://github.com/user-attachments/assets/2d7943da-6fed-4dc7-ac7a-e97679670198)
    - ![image](https://github.com/user-attachments/assets/d45b7005-6f8a-4321-a0e5-2522c2feacb4)

- 补充：因为最近才发现这个更好用的插件，不知道是否已经有了这个功能我没发现🤔

**Comment by festoney8** [comment]
下一版加入根据动态内容屏蔽动态功能
