### ISSUE TITLE
[BUG] 电影、剧集视频画面垂直不居中

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#169]
### 出问题的页面

https://www.bilibili.com/bangumi/play/ss48830

### 问题功能名

全屏时 页面可滚动（实验功能）

### 问题描述

启用“全屏时 页面可滚动（实验功能）”导致剧集视频（www.bilibili.com/bangumi/play/)在全屏和网页全屏时画面垂直不居中。变成画面居上了。

网页全屏时也不居中，跟”网页全屏时 页面可滚动“这个功能应该无关，因为开启或关闭这个功能都是一样的情况。

### 上传截图（可选）

功能关闭
![屏幕截图(31)](https://github.com/user-attachments/assets/e716511c-2fe0-408e-8c63-a184946cdb9c)

功能开启
![屏幕截图(32)](https://github.com/user-attachments/assets/2ed466cc-9150-4cae-b26f-9c03efcf3b2b)

### 操作系统

Windows 11

### 浏览器版本

Chrome 130

### 脚本管理器版本

Tampermonkey 5.3.1

### 本插件版本

v4.0.5

### 可稳定复现问题

是

### 在暴力猴/篡改猴内，只启用本脚本时，仍出现问题

是

### 禁用掉对 B 站生效的浏览器插件后，仍出现问题

否

**Comment by festoney8** [comment]
试一下 [v4.0.7](https://github.com/festoney8/bilibili-cleaner/releases/tag/v4.0.7) 还有没有这一情况

btw，全屏滚动其实是 网页全屏滚动+全屏 混合出来的，两个功能用的样式相同，只开启全屏滚动也会让网页全屏时可滚动
