### ISSUE TITLE
[Other] 保留有二级评论的包含/只含@评论

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#174]
### 文字说明

可以让“过滤 只含/包含 @其他用户 的评论”功能不过滤这种有二级评论的评论吗？
![1](https://github.com/user-attachments/assets/a21591c9-2d73-4871-9e77-d7d8c753e65c)
![2](https://github.com/user-attachments/assets/8de84877-51e6-4406-bf77-1ac481b6d5a8)

**Comment by festoney8** [comment]
加两个功能，这样OK？有没有测试链接，我翻了几个评论区还没遇到带回复的
![image](https://github.com/user-attachments/assets/1420af9d-044e-4cd5-b478-12f0e8888a76)
