### ISSUE TITLE
过滤@其他用户评论，@我的评论也被过滤了

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#177]
虽然功能叫过滤@其他用户，但是现在别人@我的评论也被过滤了……那些评论可以保留吗？

要找测试评论可以到消息中心“@ 我的”（自己发测试评论@自己，@不会生效）

**Comment by festoney8** [comment]
下一版本把自己发布的评论和自己被 AT 的评论全部忽略

对于二级评论的特殊情况，下方两张图，第一张会被当作 AT 自己，第二张不被当作 AT 自己（否则屏蔽不喜欢的用户回复会失效）

![image](https://github.com/user-attachments/assets/d319a9d6-778a-4ae7-836d-a62c32e71c3a)
![image](https://github.com/user-attachments/assets/3e6989c4-99da-415e-a9f4-ac2865cccd85)
