### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by wmtxdy** [festoney8/bilibili-cleaner#178]
### 功能描述

可以考虑一下 视频详情页右侧的标题自动展开吗
以及 视频预加载

**Comment by wmtxdy** [comment]
右边可以有左边的展示效果就好了
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月21日(星期四) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] [FR]  (Issue #178)














 
视频预加载暂不考虑，插件基本上做不出这功能
 
视频详情页右侧的标题是哪里，能否截图看一下

**Comment by wmtxdy** [comment]
b站的缓冲太慢了 -==
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月21日(星期四) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] [FR]  (Issue #178)














 
视频预加载暂不考虑，插件基本上做不出这功能
 
视频详情页右侧的标题是哪里，能否截图看一下

**Comment by festoney8** [comment]
我这里看不到，可能 Github 不支持邮件回复图片

**Comment by wmtxdy** [comment]
网页版 观看视频右侧 多视频合集 标题展开
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] [FR]  (Issue #178)














 
我这里看不到，可能 Github 不支持邮件回复图片

**Comment by festoney8** [comment]
如图，P1 是完全展开，会让列表显示的视频数量少一半，P2 是展开到两行

![image](https://github.com/user-attachments/assets/28eaabac-8e3a-4b6b-9af8-e2ccb5d82590)
![image](https://github.com/user-attachments/assets/a70ca335-8cfb-4265-8dd6-adfd11b4a83c)

还有一个方案是只展开鼠标经过的标题，如图

![image](https://github.com/user-attachments/assets/58c64d91-601a-4655-b44c-0827c4788913)

**Comment by wmtxdy** [comment]
你太棒了
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 晚上8:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] [FR]  (Issue #178)














 
如图，P1 是完全展开，会让列表显示的视频数量少一半，P2 是展开到两行
 
image.png (view on web)
 image.png (view on web)
 
还有一个方案是只展开鼠标经过的标题，如图
 
image.png (view on web)

**Comment by festoney8** [comment]
选一种吧，我不推荐完全展开，展开两行或鼠标经过展开比较舒服

**Comment by wmtxdy** [comment]
展开两行比较好 作者也有这样的需求吗
&nbsp;


1355149854
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 晚上8:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [festoney8/bilibili-cleaner] [FR]  (Issue #178)














 
选一种吧，我不推荐完全展开，展开两行或鼠标经过展开比较舒服

**Comment by festoney8** [comment]
可，下一版本加入该功能
