### ISSUE TITLE
[FR] 导入导出配置

### ISSUE THREAD

**Issue by Thrent33** [festoney8/bilibili-cleaner#181]
### 功能描述

可以增加导入和导出配置的功能吗

**Comment by festoney8** [comment]
看这里 [数据导入与导出](https://github.com/festoney8/bilibili-cleaner?tab=readme-ov-file#%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%85%A5%E4%B8%8E%E5%AF%BC%E5%87%BA)
