### ISSUE TITLE
feature: adblock-tips

### ISSUE THREAD

**Issue by dddd-zdf** [festoney8/bilibili-cleaner#21]
![image](https://github.com/festoney8/bilibili-cleaner/assets/5017696/3a4217ed-f999-4469-ad68-f66655951b9e)
![image](https://github.com/festoney8/bilibili-cleaner/assets/5017696/7416e275-1828-4d6e-ab55-9ef3692aad1b)
class="adblock-tips"

**Comment by festoney8** [comment]
Get~ 下一版本新增这一功能
