### ISSUE TITLE
 Feature Request: hide live stream on home page

### ISSUE THREAD

**Issue by niluan304** [festoney8/bilibili-cleaner#22]
能否增加一个选项，以隐藏首页的直播推荐？
![Feng_2024-01-17_20-23-06](https://github.com/festoney8/bilibili-cleaner/assets/51920864/a538212a-6ea4-4fcb-8c00-c9fc41b11585)

第二页的第一个推荐，一定是直播，这让我觉得厌烦。

**Comment by festoney8** [comment]
左上角有白色角标的 都属于分区推荐，需要开启「隐藏 视频分区推荐」这一项

**Comment by niluan304** [comment]
> 左上角有白色角标的 都属于分区推荐，需要开启「隐藏 视频分区推荐」这一项

感谢，生效了。
