### ISSUE TITLE
请问能否增加关键词过滤功能

### ISSUE THREAD

**Issue by whitewatercn** [festoney8/bilibili-cleaner#24]
比如在视频页我不想看包含某些关键词视频的推荐，但又不想关掉推荐功能
不想看包含某些关键词视频的推荐，但又不想关掉主页

希望把b站变成一个随时使用的资料库，而不是注意力吸引机

写了一点推荐：https://forum.beginner.center/t/topic/708

**Comment by whitewatercn** [comment]
> 正在做一整套视频筛选功能，现在在排bug 想体验的话，可以试一下Release中的3.0.0 alpha版本（不过不保证稳定性）

感谢回复，大佬加油💪

**Comment by festoney8** [comment]
发布了v3.0.3，测试效果比较稳定，已经更新在Greasyfork，可以试一下效果
