### ISSUE TITLE
能否提供修改首页顶栏的空白区域宽度

### ISSUE THREAD

**Issue by MeltryllisServant** [festoney8/bilibili-cleaner#30]
如题,现在顶栏的搜索栏两侧有很宽的空白区域
![image](https://github.com/festoney8/bilibili-cleaner/assets/53134695/ebce2e14-10a5-4639-9a77-38bbef77cc7d)
导致两侧的功能区域不是很明显, 能不能删除或者修改这个空白区域宽度, 让两侧的功能区域往搜索栏贴近

**Comment by festoney8** [comment]
Release里发布了v3.1.2，在全站通用项最后新增了数值调节，可以试一下
需要调节的是顶栏两端与浏览器边界的距离，搜索框两侧的空白会跟着变短
