### ISSUE TITLE
设置界面的滚动事件会传递给B站主界面

### ISSUE THREAD

**Issue by MeltryllisServant** [festoney8/bilibili-cleaner#33]
插件版本: v3.1.2 (Releases最新版)
浏览器版本: Chrome 121.0.6167.140（正式版本） （64 位）
操作步骤:
1. 打开B站
2. 打开页面净化设置
3. 滚动设置页面到最底部
4. 稍微移动鼠标(不离开设置页面), 然后再次向下滚动
此时B站主页面会发生滚动, 感觉不是很符合常见的使用逻辑, 可能是Bug?

**Comment by festoney8** [comment]
这是一个叫滚动链的web特性，已修复
