### ISSUE TITLE
请问能否添加隐藏首页所有推荐视频，只留Header和搜索栏；以及隐藏视频播放页的整个评论区？

### ISSUE THREAD

**Issue by MeleteAoide** [festoney8/bilibili-cleaner#42]

**Comment by festoney8** [comment]
隐藏整个评论区我会增加到插件中

隐藏首页所有推荐会让页面不协调，这个功能不打算加入插件

有需要的话，你可以按如下操作自行隐藏

1. 安装stylus插件 [链接](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)
2. 打开B站首页，点击stylus插件，增加脚本
3. 脚本代码填写下方这些，保存即可
```
.bili-header__channel, main {
    display: none !important;
}
```

**Comment by festoney8** [comment]
已在 v3.1.8 支持隐藏评论区

**Comment by MeleteAoide** [comment]
感谢！
