### ISSUE TITLE
疑似有BUG-已解决

### ISSUE THREAD

**Issue by gitapk890** [festoney8/bilibili-cleaner#44]
视频下方展开更多点不开
![Screenshot 2024-03-04 at 13-44-26 【开源】ESP32 墨水屏阅读器_时钟_温湿度_音乐 更新日志【10】_哔哩哔哩_bilibili](https://github.com/festoney8/bilibili-cleaner/assets/154399728/9bff3702-815f-43d2-b6a7-89f4d73c68cb)

**Comment by gitapk890** [comment]
win11，firefox123

**Comment by festoney8** [comment]
我在 Firefox 123.0 没能复现

请测试一下在插件管理器关闭本插件，刷新后功能是否正常，再开启插件，是否又会出现这一现象

**Comment by gitapk890** [comment]
已解决，是其他插件的问题，打扰了
