### ISSUE TITLE
在 search.bilibili.com/all?keyword=xxx 的 url 下，不显示视频列表的弹幕数

### ISSUE THREAD

**Issue by M1ssakira** [festoney8/bilibili-cleaner#51]
如题，在 search.bilibili.com/all?keyword=xxx 的 url 下，不显示视频列表的弹幕数，并且没有设置隐藏视频列表的弹幕数的选项。
之前好像默认设置是隐藏弹幕数，但是我手动取消了，不知道是否有关。
tampermonkey, mac os, chrome_ver: 123
<img width="1396" alt="image" src="https://github.com/festoney8/bilibili-cleaner/assets/18348211/7b9d3e2f-ec57-42b3-aec2-6afd4754f3fc">
<img width="457" alt="image" src="https://github.com/festoney8/bilibili-cleaner/assets/18348211/b01e0be4-1285-4465-a6f4-ca88cf757465">

**Comment by festoney8** [comment]
图一是搜索页截图，图二是首页设置截图，不一样呀，搜索页有自己的菜单

**Comment by M1ssakira** [comment]
my bad，糊涂了，多谢回复.
