### ISSUE TITLE
能否让视频和评论过滤列表合并为一个列表

### ISSUE THREAD

**Issue by mouse0w0** [festoney8/bilibili-cleaner#57]
首先感谢提供这个非常好用的插件。我不想看到带有某些关键词（或某些用户）的视频和评论，但是同步两个用户和关键词列表有些麻烦，能否提供一个开关让两个列表合并（或者某一列表直接使用另一列表）。

**Comment by festoney8** [comment]
#### 关于屏蔽用户

B 站的 UP 主和评论区用户是交集很低的两组用户，UP 主大多数评论发布在自己的视频下方，去其他视频评论区串门的情况很少，屏蔽 UP 主后他的视频直接消失，以后不会在任何地方见到他。

而评论区中的用户多数不发视频，他发的视频推送给你的概率更低，所以完全没必要同步这两个列表。

例外情况，深恶痛绝的用户在评论区和视频推送中都出现，右键用户名再点一下屏蔽就清净了（我屏蔽了上千个UP主，也没遇到过这种

#### 关于关键词黑名单

这两个列表只能分开维护。标题和评论是两种语言模式，只有话题性关键词是两者通用的（游戏名、人名等），其他情况，比如用正则屏蔽句法，共用列表会有未知影响。此外长列表降低全文搜索性能，尽可能保持两列表独立性，减少搜索次数比较好

这个就只能麻烦些，想同时屏蔽的关键词手动加两次吧，话题性的关键词一次加一组比较省事，[比如这种](https://github.com/festoney8/bilibili-cleaner/blob/main/NOTE.md#8-%E4%BA%8C%E6%B8%B8%E5%8E%9F%E7%A5%9E)

**Comment by mouse0w0** [comment]
好的，我先关闭这个issue，希望以后能有机会再次考虑此issue。
