### ISSUE TITLE
播放器和视频信息 交换位置(实验性) 对稍后再看视频不生效

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#73]
![屏幕截图 2024-05-23 175832](https://github.com/festoney8/bilibili-cleaner/assets/79258245/162e1876-1a0a-494c-a629-6b58c23b3249)

不知道是不是网址的问题，从稍后再看点开的视频是 www.bilibili.com/list/watchlater?

**Comment by festoney8** [comment]
已复现，这个功能确实在稍后再看页面会出问题
