### ISSUE TITLE
隐藏横幅banner后，子分区菜单被挡住了

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#78]
第一行分区按钮的子分区菜单显示在按钮上方，隐藏banner后就没有空间完整显示了。可不可以让子分区菜单像第二行分区按钮那样，显示在按钮下方？
![屏幕截图 2024-05-31 094554](https://github.com/festoney8/bilibili-cleaner/assets/79258245/8bd7ed60-468d-4b5d-86cb-2e3270e11873)

**Comment by festoney8** [comment]
这些二级菜单是动态创建的，位置由B站的代码计算出来，修改这个难度比较高。。

**Comment by festoney8** [comment]
> 我现在用 `.v-popover.is-top { top: 36px; }` 能让菜单显示在下方。
> 
> 分区按钮在不同页面宽度有3种不同高度（22px, 26px, 30px）。我尝试用下面这些规则把菜单调到合适的位置，但是不生效，控制台有报错但看不懂……
> 
> ```css
> @media ( width < 1100px ) {
>     .v-popover.is-top {
>         top: 28px;
>     }
> }
> @media ( 1100 <= width < 1701px ) {
>     .v-popover.is-top {
>         top: 32px;
>     }
> }
> @media ( 1701 <= width ) {
>     .v-popover.is-top {
>         top: 36px;
>     }
> }
> ```

这一方法确实可以在单机实现菜单栏下置，但在脚本中兼顾多种分辨率设备，在它的计算方法未知时实现并不容易

下方样式，`@media screen` 的使用有一些问题，语法可参考 https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by festoney8** [comment]
等一下，找到控制菜单下置的样式了ohhh，下一版本就更新进去
