### ISSUE TITLE
新增根据UP等级过滤的规则

### ISSUE THREAD

**Issue by JiasenLee** [festoney8/bilibili-cleaner#79]
近期B站涌入大量长ID搬运视频的账号，等级基本都在2级，因此能不能增加一个根据用户等级过滤视频的功能呢

**Comment by festoney8** [comment]
目前 B 站首页不提供 UP 主等级数据，需要逐个访问 UP 主空间才能获取到，但在脚本中这样做会对 B 站生成大量请求（会变成网络攻击），故目前无法做到按等级过滤。

这类 UP 主还是遇到一个屏蔽一个吧，可以看看他们的昵称有没有共同点、视频标题有没有共同特征，使用关键词批量屏蔽

**Comment by JiasenLee** [comment]
目前没有发现他们共性，只知道他们的UID都很长，我就先一个个屏蔽
