### ISSUE TITLE
请问能否将过滤规则应用到视频播放界面右侧推荐内容和搜索结果页面

### ISSUE THREAD

**Issue by Annnnnnia** [festoney8/bilibili-cleaner#82]
目前的过滤规则似乎只能在首页应用，请问可以将它们扩展到视频播放界面右侧的“接下来播放”和搜索页面吗

**Comment by festoney8** [comment]
首页/播放页/搜索页/热门页 都有视频过滤，但功能开关是相互独立的，在相应页面开启即可

**Comment by Annnnnnia** [comment]
抱歉之前没有留意，现在看到了谢谢 :）
