### ISSUE TITLE
对于新功能的需求

### ISSUE THREAD

**Issue by kikyou2018** [festoney8/bilibili-cleaner#83]
感谢您的工作。
能否添加动态界面的评论屏蔽功能。（很多令人恶心的、带节奏的评论在一些up主的动态里面也很多）
能否在评论屏蔽选项增加“全部屏蔽”的功能（只想圈地自己玩，不想和网络上的任何人争论，无论正面负面评论都不想看，目前一个一个添加关键词太麻烦了）。
个人建议。

**Comment by festoney8** [comment]
目前动态列表首页（ https://t.bilibili.com/ ）评论默认折叠，点击按钮查看才会展开评论，你需要的是在点进动态后的动态详情页隐藏全部评论吗？

**Comment by festoney8** [comment]
已发布 v3.7.0，动态页评论区板块新增 “隐藏整个评论区” 功能，开启后动态列表页、详情页评论区都会隐藏
