### ISSUE TITLE
新功能的建议

### ISSUE THREAD

**Issue by River-2024** [festoney8/bilibili-cleaner#84]
首先感谢作者的插件，真的很好用！！！
然后是对新功能的建议
本人比较喜欢默认宽屏，但是宽屏模式下评论区的宽度却比窄屏模式更窄，希望能加宽评论区宽度
还有就是宽屏模式下，右侧的弹幕列表和接下来播放等区域会随着滚屏固定在屏幕右下角，希望能固定在视频下方

**Comment by festoney8** [comment]
感谢支持

宽屏下评论区宽度的确会变短，宽屏相关逻辑比较复杂，我研究一下有没有解决方法。

弹幕列表和接下来播放等区域固定在视频下方，是指滚动页面时右栏不再吸附页面底部吗？这是 B 站刻意做出的效果，如果不吸附，滚动页面查看更多评论时，右栏没有视频补位会变成一片空白

**Comment by River-2024** [comment]
> 感谢支持
> 
> 宽屏下评论区宽度的确会变短，宽屏相关逻辑比较复杂，我研究一下有没有解决方法。
> 
> 弹幕列表和接下来播放等区域固定在视频下方，是指滚动页面时右栏不再吸附页面底部吗？这是 B 站刻意做出的效果，如果不吸附，滚动页面查看更多评论时，右栏没有视频补位会变成一片空白

是的，理想情况是评论区变宽来补足这一块空白
因为我是隐藏右侧接下来播放和视频推荐区域，只保留了弹幕列表，如果能不吸附+评论区变宽，看起来确实更美观简洁一些

再次感谢作者！

**Comment by festoney8** [comment]
明白你的需求了，不过目前 B 站的结构无法做到这种样子 =v=
B 站网页分成左栏（播放器、评论区）和右栏（UP主、弹幕列表、推荐视频），右栏强行占据一部分宽度，从而把页面分成两列，哪怕右侧没有元素，左栏也无法跨过分界显示到右侧空白处的

**Comment by River-2024** [comment]
受教了，谢谢你

**Comment by festoney8** [comment]
已发布 v3.7.0，新增播放设定板块，包括默认宽屏、普通模式宽度调节（普通模式播放器能调到和宽屏一样大，评论区跟随变宽），看一下有没有需要的功能

**Comment by River-2024** [comment]
> 已发布 v3.7.0，新增播放设定板块，包括默认宽屏、普通模式宽度调节（普通模式播放器能调到和宽屏一样大，评论区跟随变宽），看一下有没有需要的功能

体验了一下默认宽屏
优点是比别的插件加载明显更快
缺点是当我下滑评论区再上滑回到视频的位置，会出现横向滚动条
![screenshot-1718604433847](https://github.com/festoney8/bilibili-cleaner/assets/33181251/aed0424f-56a2-44ec-813b-5d70faf35169)

**Comment by River-2024** [comment]
> > 已发布 v3.7.0，新增播放设定板块，包括默认宽屏、普通模式宽度调节（普通模式播放器能调到和宽屏一样大，评论区跟随变宽），看一下有没有需要的功能
> 
> 感谢作者！ 体验了一下「默认宽屏」和「普通播放调节视频宽度」 优点是比别的插件加载明显更快 缺点是当我下滑评论区再上滑回到视频的位置，会出现横向滚动条，如图所示，个人感觉体验还是不理想 ![screenshot-1718604433847](https://private-user-images.githubusercontent.com/33181251/340194567-aed0424f-56a2-44ec-813b-5d70faf35169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUxMDgsIm5iZiI6MTcxODYwNDgwOCwicGF0aCI6Ii8zMzE4MTI1MS8zNDAxOTQ1NjctYWVkMDQyNGYtNTZhMi00NGVjLTgxM2ItNWQ3MGZhZjM1MTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2MTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mzg4YjJkN2VkYTc3NTE2N2E4OTQ3NGUzY2RkMWY3NzZkZTIzZTJiMDQ2NmVlM2NkNGRmZTY5YmIzYjJmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZJGmJ5B0i1bMj1P7xk1LLBglvEdNhbF_CSxbhRrXss)
> 
> 关于新功能建议，希望宽屏模式下弹幕列表能够不再吸附屏幕底部，建议增加记忆小窗播放位置的功能

**Comment by River-2024** [comment]
> 已发布 v3.7.0，新增播放设定板块，包括默认宽屏、普通模式宽度调节（普通模式播放器能调到和宽屏一样大，评论区跟随变宽），看一下有没有需要的功能

 
感谢作者！ 
体验了一下「默认宽屏」和「普通播放调节视频宽度」 
优点是比别的插件加载明显更快 
缺点是当我下滑评论区再上滑回到视频的位置，会出现横向滚动条，如图所示，个人感觉体验还是不理想 
![screenshot-1718604433847](https://private-user-images.githubusercontent.com/33181251/340194567-aed0424f-56a2-44ec-813b-5d70faf35169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUxMDgsIm5iZiI6MTcxODYwNDgwOCwicGF0aCI6Ii8zMzE4MTI1MS8zNDAxOTQ1NjctYWVkMDQyNGYtNTZhMi00NGVjLTgxM2ItNWQ3MGZhZjM1MTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA2MTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3Mzg4YjJkN2VkYTc3NTE2N2E4OTQ3NGUzY2RkMWY3NzZkZTIzZTJiMDQ2NmVlM2NkNGRmZTY5YmIzYjJmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZJGmJ5B0i1bMj1P7xk1LLBglvEdNhbF_CSxbhRrXss)
关于新功能建议，希望宽屏模式下弹幕列表能够不再吸附屏幕底部，建议增加记忆小窗播放位置的功能

**Comment by River-2024** [comment]
> 已发布 v3.7.0，新增播放设定板块，包括默认宽屏、普通模式宽度调节（普通模式播放器能调到和宽屏一样大，评论区跟随变宽），看一下有没有需要的功能

相同设置在两个视频页下出现区别，前者出现横向滚动条

![11](https://github.com/festoney8/bilibili-cleaner/assets/33181251/473e1d53-e4a4-48bd-9158-20cf98107b2e)

![2](https://github.com/festoney8/bilibili-cleaner/assets/33181251/fc00bc37-8db5-451d-8d5c-78eac64f6cdc)

**Comment by festoney8** [comment]
我在多个浏览器测试，宽度调节没能出现右侧空白异常现象，怀疑是插件冲突导致

右侧的字幕列表是插件新增的模块吗？请麻烦给出一下浏览器版本和同时使用的插件

**Comment by River-2024** [comment]
我试了一下，仅启用一个插件也会出现这样的情况
浏览器是Microsoft Edge
版本 126.0.2592.56 (正式版本) (64 位)


![1](https://github.com/festoney8/bilibili-cleaner/assets/33181251/0b23c206-afc3-4c6f-a67f-df4a7eed7f5d)
![2](https://github.com/festoney8/bilibili-cleaner/assets/33181251/6e3dd11f-4a92-40a4-b272-14902c2cc1e4)

**Comment by festoney8** [comment]
我在 Edge 126 仍未复现这一现象。从上面几张截图看，右栏的宽度始终异常，如图

![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/319b29d1-a68e-47eb-bdfa-512c199b7abb)
![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/ac570b9d-fe4c-4ffe-a561-7b84480a6e8c)
![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/380b9652-b833-421e-981f-e5e86d1a7239)

正常的宽度应是下图的样子

![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/5cc2ae99-c295-4707-8af6-c2d144c25298)

**可以试一下：**

1. 查看有没有使用对右栏生效的样式，比如 Stylus 插件，如有关掉后是否正常

2. 播放设定里的这几项功能，有哪一项启用后导致右栏宽度突变，禁用后右栏恢复？

**Comment by River-2024** [comment]
图1是正常情况，图2和图3是宽度异常情况
均没有启用任何插件

![1](https://github.com/festoney8/bilibili-cleaner/assets/33181251/11fe6ab9-29bc-4f6b-9a7d-aeefe1e3fd9c)
![2](https://github.com/festoney8/bilibili-cleaner/assets/33181251/f9d42def-dc4f-44f2-8208-c5309eff17a7)
![3](https://github.com/festoney8/bilibili-cleaner/assets/33181251/0ec3b951-dc4f-4b45-ad30-d373e50304bc)

**Comment by festoney8** [comment]
> 图1是正常情况，图2和图3是宽度异常情况 均没有启用任何插件

好的，我大概能定位到出问题的代码了

**Comment by festoney8** [comment]
已复现。右栏宽度异常的原因是使用 **默认宽屏播放 / 视频宽度调节** 时，如果没有使用 **隐藏 UP 主简介**，当简介超长时右栏会被撑宽，由于各 UP 主简介不一样长，这个现象会时有时无

将在下一版本修复

**Comment by River-2024** [comment]
我试了一下，这样确实解决问题了
关于两个新功能建议
1）弹幕列表和右侧视频推荐区域不再吸附屏幕底部
2）增加记忆小窗播放位置的功能

**Comment by festoney8** [comment]
> 我试了一下，这样确实解决问题了 关于两个新功能建议 1）弹幕列表和右侧视频推荐区域不再吸附屏幕底部 2）增加记忆小窗播放位置的功能

右栏不吸附底部已在开发版加入，小窗播放位置记忆还在测试，找到合适的方案后会加入

**Comment by River-2024** [comment]
感谢感谢
这个自动宽屏加载真的很快，很好用
期待新功能

**Comment by festoney8** [comment]
已在 v3.7.3 支持 “禁用 右栏底部吸附” 和 “记录小窗位置” 功能
