### ISSUE TITLE
隐藏直播间推荐导致推荐视频被视频小窗遮挡

### ISSUE THREAD

**Issue by nothingshiru** [festoney8/bilibili-cleaner#87]
在播放页开启“右侧 视频栏”里的“隐藏 直播间推荐”后，视频小窗会遮挡推荐视频
![屏幕截图 2024-06-18 145434](https://github.com/festoney8/bilibili-cleaner/assets/79258245/c361863d-d522-4d43-b7f4-9c292f325fe9)

我把“隐藏 直播间推荐”关闭，自己加上 `.right-container .pop-live-small-mode { display: none; }` 却没有这个问题，真奇怪
![屏幕截图 2024-06-18 145644](https://github.com/festoney8/bilibili-cleaner/assets/79258245/caa01652-891b-4ac0-8ef4-9102b6309f9d)

**Comment by festoney8** [comment]
原因大概是我在其他功能顺手修了右栏滚动页面以后的跳变问题，直接强制底部吸附了

我平常不用小窗，原以为这个空白没意义，原来它是用来放小窗播放器的

我在下一版本更新一下
