### ISSUE TITLE
评论区过滤@好友功能

### ISSUE THREAD

**Issue by HiiroYunia** [festoney8/bilibili-cleaner#90]
免过滤全关，关键词/正则似乎过滤不了@好友评论？求大佬指教，很喜欢这个插件

**Comment by festoney8** [comment]
有这个功能，在页面净化功能的评论区板块，开启即可

![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/98155a7e-cd7b-40a5-8017-53e2c2b97453)

**Comment by HiiroYunia** [comment]
是的，发完就发现了，先前一直在搞评论过滤设置，没有看页面净化设置，尴尬😂
