### ISSUE TITLE
屏蔽内容较多加载迟滞造成显示留白

### ISSUE THREAD

**Issue by Sokranotes** [festoney8/bilibili-cleaner#91]
![微信图片_20240623004422](https://github.com/festoney8/bilibili-cleaner/assets/26357162/c7d854d1-1cff-43ad-b013-4afd5bf848cb)
屏蔽了300s以下的视频，屏蔽内容较多，内容加载不及时，页面有显示留白
另，可以贴个二维码请你喝杯咖啡~

**Comment by festoney8** [comment]
确实有这一问题，目前没找到解决方法，只能降低一下时长阈值

原始首页有两部分视频，顶部默认 10 个 feed，足够填满一屏多，下方视频在滚动页面后才动态载入，开插件后只剩下一半

如果被屏蔽的视频更多，只能铺满第一行，会自动触发动态载入，但转到第二行就不一定会触发，机制很迷，目前只知道和页面内的一个锚点元素有关，如何触发仍未知

**Comment by festoney8** [comment]
发布了 v3.7.4，首页视频列表板块新增了 “预加载下一屏” 功能，试一下效果
