### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by srk24** [festoney8/bilibili-cleaner#93]
非常感谢开发者。
对于Bilibili Evolved我唯一用到的功能就是动态视频在首页排布的功能，cleaner能否提供一个这样的功能，这样就能少装点脚本了。

**Comment by srk24** [comment]
当然也理解目前有非常多的其他脚本支持我说的功能，但是还是喜欢Cleaner的UI。
如果开发者觉得此issue不合理直接close即可。感恩...

**Comment by festoney8** [comment]
感谢支持。cleaner 这个项目专注于净化和优化，让页面上的东西变少，让站点更干净是主要目标

如果加其他功能就会变成下一个和 Evolved 一样的 All in one 项目，不符合 cleaner 的初衷，所以目前不考虑做新增 xxx 功能类型的 feature
