### ISSUE TITLE
缩小「踩/回复 只在hover时显示」的触发区域

### ISSUE THREAD

**Issue by River-2024** [festoney8/bilibili-cleaner#95]
「踩/回复 只在hover时显示」触发区域太大，能不能缩小到「赞」后面一小块区域

**Comment by festoney8** [comment]
试了一下，效果不行，下图是可以用于判断 hover 行为的区域，隐藏按钮后，需要找一阵子才找到回复按钮
![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/38462625-a04e-4286-a437-f674cc8d4d61)

如果希望鼠标经过评论区不触发这些显示隐藏的跳变，我可以增加一个延迟显示的功能，比如鼠标放在评论上 0.5 秒后再显示这两个按钮

**Comment by River-2024** [comment]
增加延迟确实会好点，不然这部分内容一直跳变还挺晃眼睛的
