### ISSUE TITLE
首页的 时长过滤 没有生效

### ISSUE THREAD

**Issue by LJason77** [festoney8/bilibili-cleaner#96]
![image](https://github.com/festoney8/bilibili-cleaner/assets/11374869/790c4ab6-cef4-4cab-ba91-f0958ef62a01)

![image](https://github.com/festoney8/bilibili-cleaner/assets/11374869/e552b7e5-0701-4a60-b2f5-7063792eb22a)

非前端开发者，不太会看 F12 的日志，自己排查不出来问题。

**Comment by festoney8** [comment]
是否启用了白名单免过滤板块的功能？
![image](https://github.com/festoney8/bilibili-cleaner/assets/36254268/fdaad1ea-ae31-4a0c-acec-35f683a5ff9b)

**Comment by LJason77** [comment]
日志里有这些日志，不知道是否相关。

![image](https://github.com/festoney8/bilibili-cleaner/assets/11374869/63849ccf-ec12-4362-a2a9-72750618fbaa)

没有启用任何白名单功能。

**Comment by LJason77** [comment]
![image](https://github.com/festoney8/bilibili-cleaner/assets/11374869/38b3fd01-f302-4bd1-b13b-2fce3f3fd32e)

B站相关的脚本逐个关闭测试了，依旧不生效。

**Comment by festoney8** [comment]
请提供一下浏览器版本，可以测试一下如下功能：

1. 首页的关键词过滤是否生效
2. 播放页、搜索页的时长过滤是否生效
3. 看一下使用的首页网址是 `https://www.bilibili.com/` 还是 `https://www.bilibili.com/index.html` ，后者不会生效

**Comment by LJason77** [comment]
1. Chrome 126.0.6478.127
2. 播放页、搜索页都可以生效，只有首页不生效
3. 首页是 https://www.bilibili.com/

**Comment by LJason77** [comment]
关键词过滤也可以生效，唯独 时长过滤 没有生效

**Comment by LJason77** [comment]
关键词过滤 也只生效了一次，然后首页再也不生效了。正常尝试回忆复现之前的操作。

**Comment by festoney8** [comment]
我在相同版本 Chrome 没能复现

试一下首页的 UP主过滤和 BV 号过滤，右键单击 UP 主 / 右键单击标题 点击屏蔽以后视频是否立即消失？

**Comment by LJason77** [comment]
# 首页
- 用 https://www.bilibili.com/ 重新打开一个新标签，有一定概率生效，不生效的次数更多；
- 不管有没有生效，Ctrl+R 刷新后，一定不生效；
- 关键词过滤 和 时长过滤会一起生效或一起不生效

# 搜索页和播放页
不管什么情况，时长和关键词都能生效

**Comment by LJason77** [comment]
> 我在相同版本 Chrome 没能复现
> 
> 试一下首页的 UP主过滤和 BV 号过滤，右键单击 UP 主 / 右键单击标题 点击屏蔽以后视频是否立即消失？

只有在生效的时候，才会立刻消失。

不生效的时候，右键屏蔽没有任何反应，但是黑名单里会增加名称。

**Comment by LJason77** [comment]
排查出来了，是这个插件： https://chromewebstore.google.com/detail/%E7%9B%B8%E5%85%B3%E6%B3%95%E5%BE%8B%E6%B3%95%E8%A7%84/cgcndfhnodpingjaaofffpkblamjfojp
关闭就一切正常了

**Comment by festoney8** [comment]
> 排查出来了，是这个插件： https://chromewebstore.google.com/detail/%E7%9B%B8%E5%85%B3%E6%B3%95%E5%BE%8B%E6%B3%95%E8%A7%84/cgcndfhnodpingjaaofffpkblamjfojp 关闭就一切正常了

这也太玄学了XD

**Comment by LJason77** [comment]
当概率生效的时候，我就怀疑是不是和加载顺序有关，然后把会更改页面的插件全部排查了一遍。

可惜这个插件已经两年多没更新了。

所以这边能不能试试看兼容一下，不然就只能顶着各种恶心的缩写和和谐词了 🤣  。

**Comment by festoney8** [comment]
> 当概率生效的时候，我就怀疑是不是和加载顺序有关，然后把会更改页面的插件全部排查了一遍。
> 
> 可惜这个插件已经两年多没更新了。
> 
> 所以这边能不能试试看兼容一下，不然就只能顶着各种恶心的缩写和和谐词了 🤣 。

看了一眼，那个插件会暴力的检测所有元素文本，所以我没法兼容它只能让它别太暴力.... 目前两个插件在首页只能有一个生效

如果有能力，可以 fork 那个插件的项目，在入口文件轻微修改一下让它不在 B 站首页运行，build 一个自己的版本

**Comment by LJason77** [comment]
啊，非前端开发者劝退了。

行吧，只能二选一了。
