### ISSUE TITLE
反馈和新功能需求

### ISSUE THREAD

**Issue by HiiroYunia** [festoney8/bilibili-cleaner#97]
反馈：edge浏览器搜索页和播放页顶栏左侧新入口“时光”无法屏蔽。另外，放大网页（110%以上）会导致搜索框居左并覆盖“时光”（其他入口不会被覆盖），希望修复居左问题。

新功能需求：屏蔽直播页背景图片。小声问一句，作者有没有考虑做弹幕屏蔽功能？b站正则上限100条且有长度限制，修改麻烦，之前用的弹幕屏蔽脚本停止维护现已不可用。想知道作者有无想法或者知道其他好用的弹幕屏蔽脚本？
非常感谢作者大大的无私付出！

**Comment by festoney8** [comment]
已复现，下一版本更新“隐藏活动”功能屏蔽掉它

B 站会在网页放大到一定程度时，让时光按钮消失，同时顶栏搜索框会从居中变成居左，所以看起来像被覆盖住，实际是正常的

现在弹幕相关功能和插件足够健全，暂不考虑做弹幕屏蔽。把多条正则合并成一条吧，如果仍然束手束脚，尝试用一下 [Pakku.js](https://github.com/xmcp/pakku.js) 的高级功能，在弹幕预处理函数里执行正则，有点复杂但可定制性很高

**Comment by HiiroYunia** [comment]
下版本会解决搜索栏居左问题吗？

**Comment by festoney8** [comment]
> 下版本会解决搜索栏居左问题吗？

有需要的话我可以加个强制居中，这个简单

在我这 B 站只在 125% 缩放有搜索栏居左效果，110% 和 150% 都居中，官方代码里也是特意写的居左，我看不出它这样做有什么用意....

**Comment by HiiroYunia** [comment]
> > 下版本会解决搜索栏居左问题吗？
> 
> 有需要的话我可以加个强制居中，这个简单
> 
> 在我这 B 站只在 125% 缩放有搜索栏居左效果，110% 和 150% 都居中，官方代码里也是特意写的居左，我看不出它这样做有什么用意....

我也很疑惑为什么居左，排查了好久原因qwq

可以的话就麻烦作者了，再次感谢！
