### ISSUE TITLE
功能建议，保留高能用户/大航海 具体数量，隐藏下方拓展栏

### ISSUE THREAD

**Issue by River-2024** [festoney8/bilibili-cleaner#99]
不知道可不可以实现这样的功能，保留高能用户具体人数，但是隐藏下方高能用户具体信息的展开栏

**Comment by festoney8** [comment]
在 v3.8.0 新增了 折叠排行榜/大航海 功能，开启后折叠到只剩数量，鼠标经过时展开下方内容
